---
title: "ABC original results (from Fulco et al) over the CRISPRi-FlowFISH validation datasets"
date : "décembre 2020"
output:
  md_document
  #html_document:
    #toc: true
    #toc_float: true
    #toc_depth : 4
    #number_sections : true
---

```{css,echo=F}
.badCode {
background-color: #C9DDE4;
}
```

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
options(max.print="75")
opts_chunk$set(echo=TRUE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               class.source="badCode")
opts_knit$set(width=75)
```

```{r}
library(ggplot2)
library(ggpubr) # for ggarrange
library(dplyr) # for bind_rows

# Tools for precision-recall : (see https://classeval.wordpress.com/tools-for-roc-and-precision-recall/)
library(precrec)
#library(ROCR)
#library(pROC)
#library(PRROC)
```

```{r, results="hide"}
rm(list = ls())

# Personal
work_dir = "~/Documents/INSERM/"
# Inserm
#work_dir = "~/Documents/"

###############
## ABC Model ##
###############
#path_to_ABC_results = paste(work_dir, "ABC-Enhancer-Gene-Prediction/CRISPRi_FlowFISH/local_k562/", sep='')
path_to_ABC_results = paste(work_dir, "ABC-Enhancer-Gene-Prediction/april_K562_candidates_in_whitelist_56_genes/ABC_output/Predictions/", sep='')
#file_names_ABC = c("OLD_Predictions_over_CRISPRi_FlowFISH.bedpe")
file_names_ABC = c("predictions_intersected_with_CRISPRi_FlowFISH_regions_that_maximize_the_ABC_score.bedpe.sorted")
short_names = c('CRiFF') # CriFF stands for CRISPRi.FlowFISH

nb_files_ABC = length(file_names_ABC)
colnames_ABC <- c('interaction', 'chr', 'start', 'end', 'gene', 'ABC.Score')
abc_scores <- sapply(file_names_ABC, simplify=FALSE, function(file_name){
  Df <- read.table(paste(path_to_ABC_results, as.character(file_name), sep=''), sep='\t', header=F)
  Df[[1]] <- factor(Df[[1]], levels=c(0,1), labels=c("no interaction", "interaction"))
  names(Df) <- colnames_ABC
  #Df <- Df[complete.cases(Df$ABC.Score),]
  return(Df)
})
names(abc_scores) <- short_names

#library(dplyr)
All_results_ABC <- bind_rows(abc_scores, .id = 'dataset') # requires library(dplyr)


#####################
## Distance method ##
#####################

path_to_distance_results = paste(work_dir, "BENGI/Correlation-Methods/Average-Rank/", sep='')
file_names_distance = c("K562.CRISPRi-FlowFISH-Average-Rank.txt")

nb_files_distance = length(path_to_distance_results)

colnames_distance <- c('interaction', 'score', 'inverse.distance', 'correlation', 'inverse.distance.rank', 'correlation.rank', 'average.rank')
distance_scores <- sapply(file_names_distance, simplify=FALSE, function(file_name){
  Df <- read.table(paste(path_to_distance_results, as.character(file_name), sep=''), sep='\t')
  Df[[1]] <- factor(Df[[1]], levels=c(0,1), labels=c("no interaction", "interaction"))
  names(Df) <- colnames_distance
  return(Df)
})
names(distance_scores) <- short_names

#library(dplyr)
All_results_distance <- bind_rows(distance_scores, .id = 'method')

#####################
## Avg Rank method ##
#####################

path_to_avg_rank_results = paste(work_dir, "BENGI/Correlation-Methods/Average-Rank/", sep='')
file_names_avg_rank = c("K562.CRISPRi-FlowFISH-Average-Rank.txt")

nb_files_avg_rank = length(file_names_avg_rank)

colnames_avg_rank <- c('interaction', 'score', 'inverse.distance', 'correlation', 'inverse.distance.rank', 'correlation.rank', 'average.rank')
avg_rank_scores <- sapply(file_names_avg_rank, simplify=FALSE, function(file_name){
  Df <- read.table(paste(path_to_avg_rank_results, as.character(file_name), sep=''), sep='\t')
  Df[[1]] <- factor(Df[[1]], levels=c(0,1), labels=c("no interaction", "interaction"))
  names(Df) <- colnames_avg_rank
  return(Df)
})
names(avg_rank_scores) <- short_names

#library(dplyr)
All_results_avg_rank <- bind_rows(avg_rank_scores, .id = 'method')
```


```{r}
str(abc_scores)
summary(abc_scores$CRiFF)
```

```{r}
ggplot(aes(y = ABC.Score, x = dataset, fill = interaction), data = All_results_ABC) + geom_boxplot()
```

```{r}
sscurves_ABC <- list()
sscurves_ABC <- sapply(abc_scores, simplify=FALSE, function(Df){
  evalmod(scores = Df$ABC.Score, labels = Df$interaction) # comes with "precrec" library
})

sscurves_distance <- list()
sscurves_distance <- sapply(distance_scores, simplify=FALSE, function(Df){
  evalmod(scores = Df$inverse.distance, labels = Df$interaction) # comes with "precrec" library
})

sscurves_avg_rank <- list()
sscurves_avg_rank <- sapply(avg_rank_scores, simplify=FALSE, function(Df){
  evalmod(scores = Df$score, labels = Df$interaction) # comes with "precrec" library
})
```

```{r}
#library(ggplot2)
autoplot(sscurves_ABC[[1]], curvetype = c("PRC")) + ggtitle(paste(short_names[1], signif(attr(sscurves_ABC[[1]], 'auc')[[4]][2], digits=2), sep = " AUPR="))
autoplot(sscurves_distance[[1]], curvetype = c("PRC")) + ggtitle(paste(short_names[1], signif(attr(sscurves_distance[[1]], 'auc')[[4]][2], digits=2), sep = " AUPR="))
autoplot(sscurves_avg_rank[[1]], curvetype = c("PRC")) + ggtitle(paste(short_names[1], signif(attr(sscurves_avg_rank[[1]], 'auc')[[4]][2], digits=2), sep = " AUPR="))
```



```{r}
all_sscurves_ABC <- sapply(sscurves_ABC, simplify = FALSE, function(obj){
  Df <- data.frame(obj$prcs[[1]]$x, obj$prcs[[1]]$y)
  names(Df) <- c('x', 'y')
  return(Df)
})
all_sscurves_ABC <- bind_rows(all_sscurves_ABC, .id = 'dataset')

total_nrow = nrow(all_sscurves_ABC)
max_nb_points_to_plot = 20000
if(total_nrow>max_nb_points_to_plot){
  set.seed(1)
  samples_points = sample(1:total_nrow, min(max_nb_points_to_plot, total_nrow), replace=TRUE)
} else{
  samples_points = 1:total_nrow
}


ggplot(aes(y = y, x = x, color = dataset), data = all_sscurves_ABC[samples_points,]) + geom_line() + ylim(0,1) + xlab('Recall') + ylab('Precision') + ggtitle("Precision-Recall curves for the ABC model over the\n CRISPRi-FlowFISH validation dataset")
```

```{r}
df_sscurves_ABC <- data.frame(sscurves_ABC$CRiFF$prcs[[1]]$x, sscurves_ABC$CRiFF$prcs[[1]]$y)
names(df_sscurves_ABC) <- c('x', 'y')

total_nrow = nrow(df_sscurves_ABC)
max_nb_points_to_plot = 20000
if(total_nrow>max_nb_points_to_plot){
  set.seed(1)
  samples_points_ABC = sample(1:total_nrow, min(max_nb_points_to_plot, total_nrow), replace=TRUE)
} else{
  samples_points_ABC = 1:total_nrow
}

df_sscurves_distance <- data.frame(sscurves_distance$CRiFF$prcs[[1]]$x, sscurves_distance$CRiFF$prcs[[1]]$y)
names(df_sscurves_distance) <- c('x', 'y')

total_nrow = nrow(df_sscurves_distance)
if(total_nrow>max_nb_points_to_plot){
  set.seed(1)
  samples_points_distance = sample(1:total_nrow, min(max_nb_points_to_plot, total_nrow), replace=TRUE)
} else{
  samples_points_distance = 1:total_nrow
}

df_sscurves_avg_rank <- data.frame(sscurves_avg_rank$CRiFF$prcs[[1]]$x, sscurves_avg_rank$CRiFF$prcs[[1]]$y)
names(df_sscurves_avg_rank) <- c('x', 'y')

total_nrow = nrow(df_sscurves_avg_rank)
if(total_nrow>max_nb_points_to_plot){
  set.seed(1)
  samples_points_avg_rank = sample(1:total_nrow, min(max_nb_points_to_plot, total_nrow), replace=TRUE)
} else{
  samples_points_avg_rank = 1:total_nrow
}

ggplot(aes(y = y, x = x), data = df_sscurves_ABC[samples_points_ABC,]) + geom_line() + ylim(0,1) + xlab('Recall') + ylab('Precision') + ggtitle("Precision-Recall curves for the ABC model over the\n CRISPRi-FlowFISH validation dataset")
ggplot(aes(y = y, x = x), data = df_sscurves_distance[samples_points_distance,]) + geom_line() + ylim(0,1) + xlab('Recall') + ylab('Precision') + ggtitle("Precision-Recall curves for the Distance method over the\n CRISPRi-FlowFISH validation dataset")
ggplot(aes(y = y, x = x), data = df_sscurves_avg_rank[samples_points_avg_rank,]) + geom_line() + ylim(0,1) + xlab('Recall') + ylab('Precision') + ggtitle("Precision-Recall curves for the Avg Rank method over the\n CRISPRi-FlowFISH validation dataset")
```

```{r}
all_single_df_sscurves <- bind_rows(df_sscurves_ABC, df_sscurves_distance, .id = 'method')

fig <- ggplot(aes(y = y, x = x, col=method), data = all_single_df_sscurves) + geom_line() + ylim(0,1) + xlab('Recall') + ylab('Precision') + ggtitle("Precision-Recall over the CRISPRi-FlowFISH \n validation dataset") + labs(colour = "AUPR") + theme(legend.position = c(0.7, 0.85), legend.title = element_text(size=12), legend.text = element_text(size=12), plot.title = element_text(size=20, hjust = 0.5)) + scale_color_manual(labels = paste(c("Distance method:", "ABC model:"), c(format(round(attr(sscurves_ABC$CRiFF, 'auc')[[4]][2], 3), nsmall = 3), format(round(attr(sscurves_distance$CRiFF, 'auc')[[4]][2], 3), nsmall = 3))), values = c(2, 3))
fig
ggsave("AUPRs_ABC_Distance_over_CRiFF.png", fig, width = 8, height = 8)
```

```{r}
all_single_df_sscurves <- bind_rows(df_sscurves_ABC, df_sscurves_distance, df_sscurves_avg_rank, .id = 'method')

fig <- ggplot(aes(y = y, x = x, col=method), data = all_single_df_sscurves) + geom_line() + ylim(0,1) + xlab('Recall') + ylab('Precision') + ggtitle("Precision-Recall over the CRISPRi-FlowFISH \n validation dataset") + labs(colour = "AUPR") + theme(legend.position = c(0.7, 0.85), legend.title = element_text(size=12), legend.text = element_text(size=12), plot.title = element_text(size=20, hjust = 0.5), panel.background = element_rect(fill = "white", colour = "white",
                                size = 2, linetype = "solid"),
  panel.border = element_rect(colour = "grey", fill=NA, size=1),
  panel.grid.major = element_line(size = 0.25, linetype = 'solid',
                                colour = "grey"), 
  panel.grid.minor = element_line(size = 0.15, linetype = 'solid',
                                colour = "grey")) + scale_color_manual(labels = paste(c("ABC:", "Distance:", "Average-Rank:"), c(format(round(attr(sscurves_ABC$CRiFF, 'auc')[[4]][2], 2), nsmall = 2), format(round(attr(sscurves_distance$CRiFF, 'auc')[[4]][2], 2), nsmall = 2), format(round(attr(sscurves_avg_rank$CRiFF, 'auc')[[4]][2], 2), nsmall = 2))), values = c(2, 3, 4))
fig
ggsave("AUPRs_ABC_Distance_Avg_Rank_over_CRiFF.png", fig, width = 8, height = 8)
```




